
server:
  port: 7000
spring:
  application:
    name: sms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seremwen/School-Management-System/SMS-Config-Files
          default-label: main
          skip-ssl-validation: true
          clone-on-start: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registryFetchIntervalSeconds: 1
  instance:
    hostname: localhost

#management:
#   endpoints:
#     web:
#      exposure:
#        include: *